services:
  - type: web
    name: hr-portal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: false
      - key: GOOGLE_SHEET_ID
        value: 1M-7VE8_YvWOoCOvWM5e9z_db5UNz2ohpO8XfFRQewu8
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false   # You must paste the JSON value manually in Render dashboard
